modLoader="kotlinforforge"
loaderVersion="[1,)"
issueTrackerUrl="github.com/tilda/functionality/issues"
showAsResourcePack=false

[[mods]]
modId="functionality"
version="2.0.0"
displayName="Functionality"
credits="Forge, and thedarkcolour for Kotlin adapter"
authors="imtilda"
description='''
gamer block
'''

[[dependencies.functionality]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.functionality]]
modId="minecraft"
mandatory=true
versionRange="[1.16.1]"
ordering="NONE"
side="BOTH"